language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew check
  - ./gradlew build
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
