name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check build status
        run: echo "Result flag $FLAG_BUILD"
        env:
          FLAG_BUILD: ./build_test_script
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Generate reports
        run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacocoxml.xml # optional
          name: codecoverability
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false):  
      - name: Build with Gradle
        run: ./gradlew build
